export const env = {
  PORT: process.env.PORT ? Number(process.env.PORT) : 4000,
  NODE_ENV: process.env.NODE_ENV ?? "development",
  SUPABASE_URL: process.env.SUPABASE_URL!,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY!,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  DATABASE_URL: process.env.DATABASE_URL!,
  SUPABASE_S3_ACCESS_KEY: process.env.SUPABASE_S3_ACCESS_KEY!,
  SUPABASE_S3_SECRET_KEY: process.env.SUPABASE_S3_SECRET_KEY!,
  SUPABASE_S3_ENDPOINT: process.env.SUPABASE_S3_ENDPOINT!,
  SUPABASE_S3_PUBLIC_URL: process.env.SUPABASE_S3_PUBLIC_URL!
};